<?php

namespace App\Tests\Mocks\Repository;

use App\Repository\ProveedorRepository;
use App\Tests\Mocks\Entity\ProveedorMock;
use PHPUnit\Framework\TestCase;

class ProveedorRepositoryMock extends TestCase
{
    protected $proveedorRepositoryMock;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->proveedorRepositoryMock = $this->createMock(ProveedorRepository::class);
    }

    public static function getMock()
    {
        $proveedorRepositoryMock = new static();
        $proveedorRepositoryMock->setUp();

        $proveedorRepository = $proveedorRepositoryMock->proveedorRepositoryMock;

        $proveedorRepository->expects(self::once())
            ->method('find')
            ->willReturn(ProveedorMock::getMock())
        ;

        return $proveedorRepository;
    }
}
