<?php

namespace App\Tests\Mocks;

use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\TestCase;

class EmMock extends TestCase
{
    protected $emMock;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->emMock = $this->createMock(EntityManagerInterface::class);
    }

    public static function getMock()
    {
        $emMock = new static();
        $emMock->setUp();

        $em = $emMock->emMock;

        return $em;
    }
}