# listado de proveedores
proveedores:
  path:     /
  defaults: { _controller: App\Controller\Proveedores\proveedoresController::lista }


# formulario para crear un nuevo proveedor
proveedores_nuevo:
  path:     /new
  defaults: { _controller: App\Controller\Proveedores\proveedoresController::nuevo }
# acci贸n para crear un proveedor
proveedores_crear:
  path:     /crear
  defaults: { _controller: App\Controller\Proveedores\proveedoresController::crear }


# formulario con los datos de un proveedor
proveedor:
  path:     /{id}
  defaults: { _controller: App\Controller\Proveedores\proveedoresController::datos }
# acci贸n para editar un proveedor
proveedores_editar:
  path:     /editar/{id}
  defaults: { _controller: App\Controller\Proveedores\proveedoresController::editar }
  requirements:
    id: \d+

# acci贸n para eliminar un proveedor
proveedores_borrar:
  path:     /borrar/{id}
  defaults: { _controller: App\Controller\Proveedores\proveedoresController::borrar }
  requirements:
    id: \d+
# confirmaci贸n de proveedor borrado
proveedores_borrado:
  path:     /editar/{id}
  defaults: { _controller: App\Controller\Proveedores\proveedoresController::borrado }
  requirements:
    id: \d+
