version: '1.0'
networks:
  backend:
services:
  database:
    container_name: RL_Database
    build: ./Database/
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - backend
    tty: true
  web:
    container_name: RL_Web
    build: ./Webserver/
    ports:
      - "80:80"
    networks:
      - backend
    tty: true
