<?php

namespace App\Tests\Mocks\Entity;

use App\Entity\Tipo;
use PHPUnit\Framework\TestCase;

class TipoMock extends TestCase
{
    protected $tipoMock;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->tipoMock = $this->createMock(Tipo::class);
    }

    public static function getMock()
    {
        $tipoMock = new static();
        $tipoMock->setUp();

        $tipo = $tipoMock->tipoMock;

        $tipo->expects(self::once())
            ->method('getId')
            ->willReturn(1)
        ;
        $tipo->expects(self::once())
            ->method('getName')
            ->willReturn("Hotel")
        ;

        return $tipo;
    }
}