<?php

namespace App\Tests\Repository\Mocks;

use App\Entity\Tipo;
use App\Repository\TipoRepository;
use PHPUnit\Framework\TestCase;

class TipoRepositoryMock extends TestCase
{
    protected $tipoRepositoryMock;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->tipoRepositoryMock = $this->createMock(TipoRepository::class);
    }

    public static function getMock(Tipo $tipo)
    {
        $tipoRepositoryMock = new static();
        $tipoRepositoryMock->setUp();

        $tipoRepository = $tipoRepositoryMock->tipoRepositoryMock;

        $tipoRepository->expects(self::once())
            ->method("find")
            ->willReturn($tipo)
        ;
        return $tipoRepository;
    }
}
