<?php

namespace App\Tests\Entity\Mocks;

use App\Entity\Proveedor;
use PHPUnit\Framework\TestCase;

class ProveedorMock extends TestCase
{
    protected $tipoMock;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->tipoMock = $this->createMock(Proveedor::class);
    }

    public static function getMock()
    {
        $tipoMock = new static();
        $tipoMock->setUp();

        $proveedor = $tipoMock->tipoMock;

        $proveedor->expects(self::once())
            ->method('getId')
            ->willReturn(1)
        ;
        $proveedor->expects(self::once())
            ->method('getName')
            ->willReturn("Rodrigo")
        ;

        return $proveedor;
    }
}