<?php

namespace App\Tests\App\Proveedores;

use App\App\Proveedores\Update;
use App\Tests\Mocks\EmMock;
use App\Tests\Mocks\Entity\TipoMock;
use App\Tests\Mocks\Repository\ProveedorRepositoryMock;
use App\Tests\Mocks\Repository\TipoRepositoryMock;
use PHPUnit\Framework\TestCase;

class UpdateTest extends TestCase
{
    protected
        $tipoEntity,
        $tipoRepository,
        $proveedorRepository;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->tipoEntity          = TipoMock::getMock();
        $this->tipoRepository      = TipoRepositoryMock::getMock($this->tipoEntity);
        $this->proveedorRepository = ProveedorRepositoryMock::getMock();
        $this->em                  = EmMock::getMock();
    }


    public function testEditarEmptyException()
    {
        $class = new Update(
            $this->proveedorRepository,
            $this->tipoRepository,
            $this->em
        );

        $this->expectException("ArgumentCountError");
        /** @noinspection PhpParamsInspection */
        $class->editar();
    }

    public function testEditar()
    {
        $class = new Update(
            $this->proveedorRepository,
            $this->tipoRepository,
            $this->em
        );

        $proveedor = $class->editar([
            'id'        => 1,
            'name'      => "aaaa",
            'email'     => "bbbb@ccc.com",
            'phone'     => "654987321",
            'isActive'  => true,
            'type'      => $this->tipoEntity,
        ]);

       $this->assertInstanceOf("App\Entity\Proveedor", $proveedor);
    }
}